import { useQuery } from '@tanstack/react-query';
import { apiClient } from '@/lib/apiClient';

export interface ArticleCardData {
  id: string;
  image: string;
  category: string;
  title: string;
  author: string;
  date: string;
  slug: string;
}

// 1. Updated payload interface to match the exact 6 keys 
// generated by your Admin Landing Page Engine config
export interface HomepageSectionsPayload {
  hero: ArticleCardData[];
  latest: ArticleCardData[];
  indepth: ArticleCardData[];
  newsgrid: ArticleCardData[];
  morenews: ArticleCardData[];
  morearticles: ArticleCardData[];
}

function formatDate(dateString?: string) {
  if (!dateString) return '';
  const date = new Date(dateString);
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

/** Maps raw API story to the shape ArticleCardHorizontal / ArticleCardVertical expect */
function toCardData(article: any): ArticleCardData {
  return {
    id: article.id,
    image: article.featured_image ?? '/images/placeholder.jpg',
    // 2. IMPORTANT: Updated to `categories?.name` based on your Supabase schema fix
    category: article.categories?.name ?? 'NEWS', 
    title: article.title,
    author: article.author_name ?? 'Team Founder Diary',
    date: formatDate(article.published_at ?? article.created_at),
    slug: article.slug,
  };
}

export function useHomepageSections() {
  return useQuery({
    // Updated cache key to reflect the new dynamic engine
    queryKey: ['stories', 'dynamic-homepage'], 
    queryFn: async (): Promise<HomepageSectionsPayload> => {
      // 3. Point to the new dynamic endpoint (adjust path if your apiClient automatically prepends '/api')
      const response: any = await apiClient.get('/homepage'); 
      
      // Safely extract the data depending on how your apiClient formats responses
      const payload = response.data || response.payload || response;

      return {
        hero: (payload.hero || []).map(toCardData),
        latest: (payload.latest || []).map(toCardData),
        indepth: (payload.indepth || []).map(toCardData),
        newsgrid: (payload.newsgrid || []).map(toCardData),
        morenews: (payload.morenews || []).map(toCardData),
        morearticles: (payload.morearticles || []).map(toCardData),
      };
    },
    staleTime: 1000 * 60 * 5, // Cache for 5 minutes for blazing fast navigation
  });
}